// Diagram specs for claude_concepts_guide.md. `block` is the Mermaid block's position in the guide.
// Title text inside [[...]] renders in the accent green.
module.exports = [
  {
    name: 'slash-commands-file-structure',
    block: 2,
    alt: 'Slash command file structure: the project root contains .claude/commands/, which holds command files and a docs/ subfolder of namespaced commands',
    eyebrow: 'Slash Commands · File Structure',
    title: 'Where [[commands]] live',
    sub: 'Every Markdown file in .claude/commands/ becomes a slash command.',
    layout: 'graph',
    colgap: 130,
    cardMax: 300,
    columns: [
      { label: 'Project', nodes: [{ id: 'root', icon: 'home', title: 'Project Root', chip: 'my-project/' }] },
      { label: 'Commands folder', nodes: [{ id: 'cmds', icon: 'folder', title: 'Commands', chip: '.claude/commands/' }] },
      {
        label: 'Files',
        nodes: [
          { id: 'opt', icon: 'file', title: 'optimize.md', chip: '/optimize' },
          { id: 'test', icon: 'file', title: 'test.md', chip: '/test' },
          { id: 'docs', icon: 'folder', title: 'docs/', chip: 'subfolder' },
        ],
      },
      {
        label: 'Namespaced',
        nodes: [
          { id: 'api', icon: 'file', title: 'generate-api-docs.md', chip: '/generate-api-docs' },
          { id: 'readme', icon: 'file', title: 'generate-readme.md', chip: '/generate-readme', accent: true },
        ],
      },
    ],
    edges: [
      { from: 'root', to: 'cmds', label: 'contains' },
      { from: 'cmds', to: 'opt' },
      { from: 'cmds', to: 'test' },
      { from: 'cmds', to: 'docs' },
      { from: 'docs', to: 'api' },
      { from: 'docs', to: 'readme' },
    ],
    footer: '<b>Project</b> <code>.claude/commands/</code> &nbsp;·&nbsp; <b>Personal</b> <code>~/.claude/commands/</code>',
  },
  {
    name: 'slash-commands-lifecycle',
    block: 3,
    alt: 'Slash command lifecycle: the user types /optimize, Claude Code loads optimize.md from the file system, may run shell scripts, and returns the analysis',
    eyebrow: 'Slash Commands · Lifecycle',
    title: 'The life of [[/optimize]]',
    sub: 'From typing the command to getting the analysis back.',
    layout: 'sequence',
    participants: [
      { id: 'user', icon: 'user', title: 'User' },
      { id: 'claude', icon: 'cpu', title: 'Claude Code', accent: true },
      { id: 'fs', icon: 'folder', title: 'File System' },
      { id: 'cli', icon: 'terminal', title: 'Shell / Bash' },
    ],
    steps: [
      { from: 'user', to: 'claude', label: 'Types /optimize' },
      { from: 'claude', to: 'fs', label: 'Searches .claude/commands/' },
      { from: 'fs', to: 'claude', label: 'Returns optimize.md', dashed: true },
      { from: 'claude', to: 'claude', label: 'Loads Markdown content' },
      { from: 'claude', to: 'user', label: 'Displays prompt context' },
      { from: 'user', to: 'claude', label: 'Provides code to analyze' },
      { from: 'claude', to: 'cli', label: '(May execute scripts)' },
      { from: 'cli', to: 'claude', label: 'Results', dashed: true },
      { from: 'claude', to: 'user', label: 'Returns analysis' },
    ],
  },
  {
    name: 'subagents-architecture',
    block: 4,
    alt: 'Subagent architecture: the user asks the main agent, which delegates to code reviewer, test engineer, and documentation subagents and synthesizes their results',
    eyebrow: 'Subagents · Architecture',
    title: 'One coordinator, [[many specialists]]',
    sub: 'The main agent delegates work and synthesizes what comes back.',
    layout: 'graph',
    colgap: 190,
    cardMax: 320,
    columns: [
      { label: 'You', nodes: [{ id: 'user', icon: 'user', title: 'User' }] },
      { label: 'Coordinator', nodes: [{ id: 'main', icon: 'target', title: 'Main Agent', chip: 'coordinator', accent: true }] },
      {
        label: 'Subagents',
        nodes: [
          { id: 'rev', icon: 'search', title: 'Code Reviewer', chip: 'subagent' },
          { id: 'test', icon: 'check', title: 'Test Engineer', chip: 'subagent' },
          { id: 'docs', icon: 'edit', title: 'Documentation', chip: 'subagent' },
        ],
      },
    ],
    edges: [
      { from: 'user', to: 'main', label: 'asks' },
      { from: 'main', to: 'user', label: 'synthesizes', dashed: true },
      { from: 'main', to: 'rev' },
      { from: 'main', to: 'test', label: 'delegates' },
      { from: 'main', to: 'docs' },
      { from: 'rev', to: 'main', dashed: true },
      { from: 'test', to: 'main', label: 'returns result', dashed: true },
      { from: 'docs', to: 'main', dashed: true },
    ],
  },
  {
    name: 'subagents-lifecycle',
    block: 5,
    alt: 'Subagent lifecycle: the main agent hands a review to the code reviewer subagent, which starts a clean context window, performs the review, and returns findings',
    eyebrow: 'Subagents · Lifecycle',
    title: 'A delegated task, [[step by step]]',
    sub: 'The subagent works in its own clean context and returns only its findings.',
    layout: 'sequence',
    participants: [
      { id: 'user', icon: 'user', title: 'User' },
      { id: 'main', icon: 'target', title: 'Main Agent', accent: true },
      { id: 'rev', icon: 'search', title: 'Code Reviewer', chip: 'subagent' },
      { id: 'ctx', icon: 'layers', title: 'Context Window', chip: 'separate' },
    ],
    steps: [
      { from: 'user', to: 'main', label: '"Build new auth feature"' },
      { from: 'main', to: 'main', label: 'Analyze task' },
      { from: 'main', to: 'rev', label: '"Review this code"' },
      { from: 'rev', to: 'ctx', label: 'Initialize clean context' },
      { from: 'ctx', to: 'rev', label: 'Load reviewer instructions' },
      { from: 'rev', to: 'rev', label: 'Perform review' },
      { from: 'rev', to: 'main', label: 'Return findings', dashed: true },
      { from: 'main', to: 'main', label: 'Incorporate results' },
      { from: 'main', to: 'user', label: 'Provide synthesis', dashed: true },
    ],
  },
  {
    name: 'subagents-tool-access',
    block: 6,
    alt: 'Subagent tool access: a subagent either inherits all tools from the main thread (file operations, shell commands, MCP tools) or gets an explicit list of tools',
    eyebrow: 'Subagents · Tool Access',
    title: 'Which [[tools]] a subagent gets',
    sub: 'Inherit everything from the main thread, or list exactly what it may use.',
    layout: 'graph',
    colgap: 170,
    cardMax: 340,
    columns: [
      { label: 'Config', nodes: [{ id: 'cfg', icon: 'sliders', title: 'Subagent Configuration' }] },
      {
        label: 'Options',
        nodes: [
          { id: 'inh', icon: 'layers', title: 'Inherit All Tools', chip: 'from main thread' },
          { id: 'spec', icon: 'list', title: 'Specify Individual Tools', chip: 'explicit list', accent: true },
        ],
      },
      {
        label: 'Resulting tools',
        nodes: [
          { id: 'b1', icon: 'file', title: 'File Operations' },
          { id: 'b2', icon: 'terminal', title: 'Shell Commands' },
          { id: 'b3', icon: 'server', title: 'MCP Tools' },
          { id: 'c1', icon: 'check', title: 'Read-only set', chip: 'read, grep, diff' },
          { id: 'c2', icon: 'check', title: 'Scoped Bash', chip: 'Bash(npm:*), Bash(test:*)' },
        ],
      },
    ],
    edges: [
      { from: 'cfg', to: 'inh', label: 'option 1' },
      { from: 'cfg', to: 'spec', label: 'option 2' },
      { from: 'inh', to: 'b1' },
      { from: 'inh', to: 'b2', label: 'includes' },
      { from: 'inh', to: 'b3' },
      { from: 'spec', to: 'c1' },
      { from: 'spec', to: 'c2' },
    ],
  },
  {
    name: 'subagents-context',
    block: 7,
    alt: 'Subagent context management: the main agent context hands each subagent a clean slate, and each subagent sends back only its results',
    eyebrow: 'Subagents · Context',
    title: 'Clean slates, [[results only]]',
    sub: 'Each subagent starts fresh, so its work never fills the main context.',
    layout: 'graph',
    colgap: 260,
    cardMax: 340,
    columns: [
      { label: 'Main', nodes: [{ id: 'main', icon: 'layers', title: 'Main Agent Context', chip: '50,000 tokens', accent: true }] },
      {
        label: 'Subagents',
        nodes: [
          { id: 's1', icon: 'cpu', title: 'Subagent 1 Context', chip: '20,000 tokens' },
          { id: 's2', icon: 'cpu', title: 'Subagent 2 Context', chip: '20,000 tokens' },
          { id: 's3', icon: 'cpu', title: 'Subagent 3 Context', chip: '20,000 tokens' },
        ],
      },
    ],
    edges: [
      { from: 'main', to: 's1' },
      { from: 'main', to: 's2', label: 'clean slate' },
      { from: 'main', to: 's3' },
      { from: 's1', to: 'main', dashed: true },
      { from: 's2', to: 'main', label: 'results only', dashed: true },
      { from: 's3', to: 'main', dashed: true },
    ],
  },
  {
    name: 'memory-architecture',
    block: 8,
    alt: 'Memory architecture: user input flows into the memory system, which synthesizes into memory storage every 24 hours; storage loads into each Claude session, which feeds context back into the memory system',
    eyebrow: 'Memory · Architecture',
    title: 'How [[memory]] flows',
    sub: 'What you share is synthesized, stored, and loaded into later sessions.',
    layout: 'graph',
    colgap: 150,
    cardMax: 300,
    columns: [
      { nodes: [{ id: 'in', icon: 'user', title: 'User Input' }] },
      { nodes: [{ id: 'sys', icon: 'cpu', title: 'Memory System', accent: true }] },
      { nodes: [{ id: 'store', icon: 'database', title: 'Memory Storage' }] },
      { nodes: [{ id: 'sess', icon: 'message', title: 'Claude Session' }] },
    ],
    edges: [
      { from: 'in', to: 'sys', label: 'provides info' },
      { from: 'sys', to: 'store', label: 'every 24h' },
      { from: 'store', to: 'sess', label: 'loads auto' },
      { from: 'sess', to: 'sys', label: 'uses context' },
    ],
  },
  {
    name: 'memory-hierarchy',
    block: 9,
    alt: 'Memory hierarchy in Claude Code: seven tiers from highest to lowest priority, managed policy, project memory, project rules, user memory, user rules, local memory, and auto memory',
    eyebrow: 'Memory · Hierarchy',
    title: 'Seven tiers, [[highest priority first]]',
    sub: 'Claude Code loads memory from all seven; higher tiers win on conflicts.',
    layout: 'graph',
    colgap: 26,
    cardMax: 220,
    dense: true,
    vertical: true,
    columns: [
      { label: 'Highest', nodes: [{ id: 't1', icon: 'shield', title: 'Managed Policy', chip: 'enterprise admin', num: '1', accent: true }] },
      { nodes: [{ id: 't2', icon: 'file', title: 'Project Memory', chip: './CLAUDE.md', num: '2' }] },
      { nodes: [{ id: 't3', icon: 'list', title: 'Project Rules', chip: '.claude/rules/*.md', num: '3' }] },
      { nodes: [{ id: 't4', icon: 'user', title: 'User Memory', chip: '~/.claude/CLAUDE.md', num: '4' }] },
      { nodes: [{ id: 't5', icon: 'list', title: 'User Rules', chip: '~/.claude/rules/*.md', num: '5' }] },
      { nodes: [{ id: 't6', icon: 'monitor', title: 'Local Memory', chip: './CLAUDE.local.md', num: '6' }] },
      { label: 'Lowest', nodes: [{ id: 't7', icon: 'zap', title: 'Auto Memory', chip: 'learned prefs', num: '7' }] },
    ],
    edges: [
      { from: 't1', to: 't2' },
      { from: 't2', to: 't3' },
      { from: 't3', to: 't4' },
      { from: 't4', to: 't5' },
      { from: 't5', to: 't6' },
      { from: 't6', to: 't7' },
    ],
  },
  {
    name: 'memory-update-lifecycle',
    block: 10,
    alt: 'Memory update lifecycle: the user asks Claude Code to remember a rule, picks project memory, and Claude writes it to ./CLAUDE.md and reloads memory',
    eyebrow: 'Memory · Updates',
    title: 'Saving a [[memory]]',
    sub: 'From "remember this" to an updated CLAUDE.md.',
    layout: 'sequence',
    participants: [
      { id: 'user', icon: 'user', title: 'User' },
      { id: 'claude', icon: 'cpu', title: 'Claude Code', accent: true },
      { id: 'fs', icon: 'folder', title: 'File System' },
      { id: 'mem', icon: 'file', title: 'CLAUDE.md' },
    ],
    steps: [
      { from: 'user', to: 'claude', label: '"Remember: use async/await"' },
      { from: 'claude', to: 'user', label: '"Which memory file?"' },
      { from: 'user', to: 'claude', label: '"Project memory"' },
      { from: 'claude', to: 'fs', label: 'Open ~/.claude/settings.json' },
      { from: 'claude', to: 'mem', label: 'Write to ./CLAUDE.md' },
      { from: 'mem', to: 'claude', label: 'File saved', dashed: true },
      { from: 'claude', to: 'claude', label: 'Load updated memory' },
      { from: 'claude', to: 'user', label: '"Memory saved!"', dashed: true },
    ],
  },
  {
    name: 'memory-synthesis-timeline',
    block: 11,
    alt: 'Memory synthesis timeline in Claude web and desktop: day 1 conversations are synthesized after 24 hours, loaded into new conversations, and refreshed again 24 hours later',
    eyebrow: 'Memory · Web & Desktop',
    title: 'The [[24-hour]] synthesis cycle',
    sub: 'In Claude web and desktop, memory is summarized automatically each day.',
    layout: 'graph',
    colgap: 120,
    cardMax: 220,
    dense: true,
    vertical: true,
    columns: [
      { nodes: [{ id: 'a', icon: 'message', title: 'Conversations', chip: 'Day 1' }] },
      { nodes: [{ id: 'b', icon: 'cpu', title: 'Memory Synthesis', chip: 'Day 2' }] },
      { nodes: [{ id: 'c', icon: 'database', title: 'Memory Updated', chip: 'summarized' }] },
      { nodes: [{ id: 'd', icon: 'message', title: 'New Conversations', chip: 'Day 2–N' }] },
      { nodes: [{ id: 'e', icon: 'layers', title: 'Memory', chip: 'grows' }] },
      { nodes: [{ id: 'f', icon: 'refresh', title: 'Memory Refreshed', chip: 'next cycle', accent: true }] },
    ],
    edges: [
      { from: 'a', to: 'b', label: '24 hours' },
      { from: 'b', to: 'c', label: 'automatic' },
      { from: 'c', to: 'd', label: 'loaded in' },
      { from: 'd', to: 'e', label: 'add to' },
      { from: 'e', to: 'f', label: '24h later' },
    ],
  },
  {
    name: 'mcp-architecture',
    block: 12,
    alt: 'MCP architecture: Claude sends tool requests such as list_issues and create_issue to an MCP server, which queries or acts on an external service and returns the response',
    eyebrow: 'MCP · Architecture',
    title: 'Claude ⇄ [[MCP]] ⇄ the world',
    sub: 'An MCP server translates tool calls into real requests to an external service.',
    layout: 'graph',
    colgap: 230,
    cardMax: 330,
    columns: [
      { label: 'Client', nodes: [{ id: 'claude', icon: 'cpu', title: 'Claude', chip: 'tool call' }] },
      { label: 'Bridge', nodes: [{ id: 'mcp', icon: 'server', title: 'MCP Server', chip: 'list_issues · create_issue', accent: true }] },
      { label: 'Service', nodes: [{ id: 'svc', icon: 'globe', title: 'External Service', chip: 'e.g. GitHub API' }] },
    ],
    edges: [
      { from: 'claude', to: 'mcp', label: 'request' },
      { from: 'mcp', to: 'claude', label: 'response', dashed: true },
      { from: 'mcp', to: 'svc', label: 'query / action' },
      { from: 'svc', to: 'mcp', label: 'data / result', dashed: true },
    ],
  },
  {
    name: 'mcp-ecosystem',
    block: 13,
    alt: 'MCP ecosystem: Claude connects over MCP to filesystem, GitHub, database, Slack, and Google Docs servers, each fronting local files, repos, SQL databases, a Slack workspace, or Google Drive',
    eyebrow: 'MCP · Ecosystem',
    title: 'One protocol, [[many servers]]',
    sub: 'Each MCP server gives Claude live access to one system.',
    layout: 'graph',
    colgap: 170,
    cardMax: 320,
    rowgap: 14,
    columns: [
      { label: 'Client', nodes: [{ id: 'claude', icon: 'cpu', title: 'Claude', accent: true }] },
      {
        label: 'MCP servers',
        nodes: [
          { id: 'fs', icon: 'folder', title: 'Filesystem', chip: 'MCP server' },
          { id: 'gh', icon: 'git', title: 'GitHub', chip: 'MCP server' },
          { id: 'db', icon: 'database', title: 'Database', chip: 'MCP server' },
          { id: 'sl', icon: 'message', title: 'Slack', chip: 'MCP server' },
          { id: 'gd', icon: 'file', title: 'Google Docs', chip: 'MCP server' },
        ],
      },
      {
        label: 'Systems',
        nodes: [
          { id: 'files', icon: 'file', title: 'Local Files' },
          { id: 'repos', icon: 'git', title: 'GitHub Repos' },
          { id: 'sql', icon: 'database', title: 'PostgreSQL / MySQL' },
          { id: 'ws', icon: 'users', title: 'Slack Workspace' },
          { id: 'drive', icon: 'globe', title: 'Google Drive' },
        ],
      },
    ],
    edges: [
      { from: 'claude', to: 'fs' },
      { from: 'claude', to: 'gh' },
      { from: 'claude', to: 'db', label: 'MCP' },
      { from: 'claude', to: 'sl' },
      { from: 'claude', to: 'gd' },
      { from: 'fs', to: 'files', label: 'file I/O' },
      { from: 'gh', to: 'repos', label: 'API' },
      { from: 'db', to: 'sql', label: 'query' },
      { from: 'sl', to: 'ws', label: 'messages' },
      { from: 'gd', to: 'drive', label: 'docs' },
    ],
  },
  {
    name: 'mcp-setup',
    block: 14,
    alt: 'MCP setup process: the user runs /mcp, selects the GitHub server, Claude Code updates the config, tests the connection, and confirms it is connected',
    eyebrow: 'MCP · Setup',
    title: 'Connecting an [[MCP server]]',
    sub: 'From /mcp to a tested, authenticated connection.',
    layout: 'sequence',
    participants: [
      { id: 'user', icon: 'user', title: 'User' },
      { id: 'claude', icon: 'cpu', title: 'Claude Code', accent: true },
      { id: 'cfg', icon: 'sliders', title: 'Config File' },
      { id: 'svc', icon: 'globe', title: 'External Service' },
    ],
    steps: [
      { from: 'user', to: 'claude', label: 'Types /mcp' },
      { from: 'claude', to: 'claude', label: 'Lists available MCP servers' },
      { from: 'claude', to: 'user', label: 'Shows options' },
      { from: 'user', to: 'claude', label: 'Selects GitHub MCP' },
      { from: 'claude', to: 'cfg', label: 'Updates configuration' },
      { from: 'cfg', to: 'claude', label: 'Activates connection' },
      { from: 'claude', to: 'svc', label: 'Tests connection' },
      { from: 'svc', to: 'claude', label: 'Authentication successful', dashed: true },
      { from: 'claude', to: 'user', label: '✓ MCP connected!' },
    ],
  },
  {
    name: 'mcp-vs-memory',
    block: 15,
    alt: 'MCP versus memory decision: if you do not need external data, or it rarely changes, use memory for preferences, context, and history; if it changes often, use MCP for live APIs, databases, and services',
    eyebrow: 'MCP vs Memory · Decision',
    title: 'Memory or [[MCP]]?',
    sub: 'Two questions decide it: is the data external, and does it change often?',
    layout: 'graph',
    colgap: 150,
    cardMax: 320,
    rowgap: 40,
    columns: [
      { nodes: [{ id: 'q1', q: true, title: 'Need external data?' }] },
      { nodes: [{ id: 'sp', spacer: true, title: 'x', chip: 'x' }, { id: 'q2', q: true, title: 'Changes frequently?' }] },
      {
        nodes: [
          { id: 'mem', icon: 'database', title: 'Use Memory' },
          { id: 'mcp', icon: 'server', title: 'Use MCP', accent: true },
        ],
      },
      {
        nodes: [
          { id: 'stores', icon: 'layers', title: 'Stores', desc: 'Preferences · Context · History' },
          { id: 'access', icon: 'globe', title: 'Accesses', desc: 'Live APIs · Databases · Services' },
        ],
      },
    ],
    edges: [
      { from: 'q1', to: 'mem', label: 'no' },
      { from: 'q1', to: 'q2', label: 'yes' },
      { from: 'q2', to: 'mem', label: 'rarely' },
      { from: 'q2', to: 'mcp', label: 'often' },
      { from: 'mem', to: 'stores' },
      { from: 'mcp', to: 'access' },
    ],
  },
  {
    name: 'mcp-request-response',
    block: 16,
    alt: 'MCP request and response pattern: Claude sends a SQL query to the MCP server, which runs it against the database in real time and returns parsed data',
    eyebrow: 'MCP · Request / Response',
    title: 'A live query, [[end to end]]',
    sub: 'Data comes straight from the source on every request.',
    layout: 'sequence',
    participants: [
      { id: 'app', icon: 'cpu', title: 'Claude', accent: true },
      { id: 'mcp', icon: 'server', title: 'MCP Server' },
      { id: 'db', icon: 'database', title: 'Database' },
    ],
    steps: [
      { from: 'app', to: 'mcp', label: 'Request: "SELECT * FROM users WHERE id=1"' },
      { from: 'mcp', to: 'db', label: 'Execute query' },
      { from: 'db', to: 'mcp', label: 'Result set', dashed: true },
      { from: 'mcp', to: 'app', label: 'Return parsed data', dashed: true },
      { from: 'app', to: 'app', label: 'Process result' },
      { from: 'app', to: 'app', label: 'Continue task' },
      { note: 'Real-time access · No caching', over: ['mcp', 'db'] },
    ],
  },
  {
    name: 'skills-architecture',
    block: 17,
    alt: 'Skill architecture: a skill directory contains SKILL.md, which holds YAML metadata and instructions, plus optional scripts and templates',
    eyebrow: 'Skills · Architecture',
    title: 'Inside a [[skill]]',
    sub: 'A folder with SKILL.md at its core, plus any scripts and templates it needs.',
    layout: 'graph',
    colgap: 170,
    cardMax: 330,
    columns: [
      { label: 'Folder', nodes: [{ id: 'dir', icon: 'folder', title: 'Skill Directory', chip: 'my-skill/' }] },
      {
        label: 'Contains',
        nodes: [
          { id: 'skill', icon: 'file', title: 'SKILL.md', chip: 'required', accent: true },
          { id: 'scripts', icon: 'code', title: 'Scripts', chip: 'optional' },
          { id: 'tpl', icon: 'layers', title: 'Templates', chip: 'optional' },
        ],
      },
      {
        label: 'SKILL.md holds',
        nodes: [
          { id: 'yaml', icon: 'list', title: 'YAML Metadata', chip: 'name · description' },
          { id: 'instr', icon: 'book', title: 'Instructions', chip: 'Markdown body' },
        ],
      },
    ],
    edges: [
      { from: 'dir', to: 'skill' },
      { from: 'dir', to: 'scripts' },
      { from: 'dir', to: 'tpl' },
      { from: 'skill', to: 'yaml' },
      { from: 'skill', to: 'instr' },
    ],
  },
  {
    name: 'skills-loading',
    block: 18,
    alt: 'Skill loading process: for a request to create an Excel report, Claude scans skill metadata, matches the xlsx skill, loads its SKILL.md, executes it, and generates the file',
    eyebrow: 'Skills · Loading',
    title: 'How a [[skill]] gets picked',
    sub: 'Claude reads only metadata first, then loads the one skill it needs.',
    layout: 'sequence',
    participants: [
      { id: 'user', icon: 'user', title: 'User' },
      { id: 'claude', icon: 'cpu', title: 'Claude', accent: true },
      { id: 'sys', icon: 'grid', title: 'System' },
      { id: 'skill', icon: 'zap', title: 'Skill', chip: 'xlsx' },
    ],
    steps: [
      { from: 'user', to: 'claude', label: '"Create Excel report"' },
      { from: 'claude', to: 'sys', label: 'Scan available skills' },
      { from: 'sys', to: 'sys', label: 'Load skill metadata' },
      { from: 'claude', to: 'claude', label: 'Match request to skills' },
      { from: 'claude', to: 'skill', label: 'Load xlsx skill SKILL.md' },
      { from: 'skill', to: 'claude', label: 'Return instructions + tools', dashed: true },
      { from: 'claude', to: 'claude', label: 'Execute skill' },
      { from: 'claude', to: 'user', label: 'Generate Excel file' },
    ],
  },
  {
    name: 'skills-prebuilt',
    block: 19,
    alt: 'Pre-built skills: PowerPoint for creating and editing slides, Excel for spreadsheets and data analysis, Word for documents and formatting, and PDF for generating PDFs and filling forms',
    eyebrow: 'Skills · Pre-built',
    title: 'Four [[pre-built]] skills',
    sub: 'Document skills that work without any setup.',
    layout: 'graph',
    colgap: 220,
    cardMax: 420,
    rowgap: 16,
    columns: [
      { nodes: [{ id: 'root', icon: 'package', title: 'Pre-built Skills', accent: true }] },
      {
        nodes: [
          { id: 'pptx', icon: 'monitor', title: 'PowerPoint', chip: 'pptx', desc: 'Create presentations · Edit slides' },
          { id: 'xlsx', icon: 'table', title: 'Excel', chip: 'xlsx', desc: 'Create spreadsheets · Analyze data' },
          { id: 'docx', icon: 'file', title: 'Word', chip: 'docx', desc: 'Create documents · Format text' },
          { id: 'pdf', icon: 'book', title: 'PDF', chip: 'pdf', desc: 'Generate PDFs · Fill forms' },
        ],
      },
    ],
    edges: [
      { from: 'root', to: 'pptx' },
      { from: 'root', to: 'xlsx' },
      { from: 'root', to: 'docx' },
      { from: 'root', to: 'pdf' },
    ],
  },
  {
    name: 'skills-discovery',
    block: 20,
    alt: 'Skill discovery: Claude scans available skills and checks each description; on a match it loads SKILL.md and executes the skill, otherwise it tries the next skill or falls back to general knowledge',
    eyebrow: 'Skills · Discovery',
    title: 'Match, load, [[execute]]',
    sub: 'Claude checks skill descriptions until one fits the request.',
    layout: 'graph',
    colgap: 135,
    cardMax: 250,
    rowgap: 80,
    dense: true,
    columns: [
      { nodes: [{ id: 'req', icon: 'user', title: 'User Request' }] },
      { nodes: [{ id: 'avail', icon: 'search', title: 'Available Skills', chip: 'scanned' }] },
      { nodes: [{ id: 'match', q: true, title: 'Description match?' }] },
      {
        nodes: [
          { id: 'load', icon: 'file', title: 'Load SKILL.md' },
          { id: 'next', icon: 'refresh', title: 'Try Next Skill' },
        ],
      },
      {
        nodes: [
          { id: 'exec', icon: 'play', title: 'Execute Skill', chip: 'instructions' },
          { id: 'gen', icon: 'book', title: 'General Knowledge', chip: 'fallback' },
        ],
      },
      { nodes: [{ id: 'done', icon: 'check', title: 'Return Results', accent: true }] },
    ],
    edges: [
      { from: 'req', to: 'avail' },
      { from: 'avail', to: 'match', label: 'metadata' },
      { from: 'match', to: 'load', label: 'yes' },
      { from: 'match', to: 'next', label: 'no' },
      { from: 'next', to: 'match', label: 'more', dashed: true },
      { from: 'next', to: 'gen', label: 'no more' },
      { from: 'load', to: 'exec', label: 'extract' },
      { from: 'exec', to: 'done' },
    ],
  },
  {
    name: 'skills-vs-features',
    block: 21,
    alt: 'Skills compared with other features: slash commands are user-invoked shortcuts, subagents are auto-delegated isolated contexts, memory is persistent cross-session context, MCP is real-time external data, and skills are auto-invoked autonomous execution',
    eyebrow: 'Skills · Compared',
    title: 'Five ways to [[extend Claude]]',
    sub: 'How each feature is triggered, and what it gives you.',
    layout: 'graph',
    colgap: 170,
    cardMax: 330,
    rowgap: 14,
    columns: [
      { label: 'Goal', nodes: [{ id: 'root', icon: 'zap', title: 'Extending Claude' }] },
      {
        label: 'Feature',
        nodes: [
          { id: 'cmd', icon: 'terminal', title: 'Slash Commands', chip: 'user-invoked' },
          { id: 'sub', icon: 'users', title: 'Subagents', chip: 'auto-delegated' },
          { id: 'mem', icon: 'database', title: 'Memory', chip: 'persistent' },
          { id: 'mcp', icon: 'server', title: 'MCP', chip: 'real-time' },
          { id: 'skill', icon: 'star', title: 'Skills', chip: 'auto-invoked', accent: true },
        ],
      },
      {
        label: 'Gives you',
        nodes: [
          { id: 'g1', icon: 'zap', title: 'Quick shortcuts' },
          { id: 'g2', icon: 'layers', title: 'Isolated contexts' },
          { id: 'g3', icon: 'clock', title: 'Cross-session context' },
          { id: 'g4', icon: 'globe', title: 'External data access' },
          { id: 'g5', icon: 'play', title: 'Autonomous execution' },
        ],
      },
    ],
    edges: [
      { from: 'root', to: 'cmd' },
      { from: 'root', to: 'sub' },
      { from: 'root', to: 'mem' },
      { from: 'root', to: 'mcp' },
      { from: 'root', to: 'skill' },
      { from: 'cmd', to: 'g1' },
      { from: 'sub', to: 'g2' },
      { from: 'mem', to: 'g3' },
      { from: 'mcp', to: 'g4' },
      { from: 'skill', to: 'g5' },
    ],
  },
  {
    name: 'plugins-architecture',
    block: 22,
    alt: 'Plugin architecture: a plugin bundles slash commands, subagents, MCP servers, hooks, and configuration into one installable package',
    eyebrow: 'Plugins · Architecture',
    title: 'One plugin, [[everything bundled]]',
    sub: 'Commands, agents, servers, hooks, and settings install together.',
    layout: 'graph',
    colgap: 240,
    cardMax: 360,
    rowgap: 14,
    columns: [
      { label: 'Package', nodes: [{ id: 'p', icon: 'package', title: 'Plugin', chip: '.claude-plugin/plugin.json', accent: true }] },
      {
        label: 'Bundles',
        nodes: [
          { id: 'cmd', icon: 'terminal', title: 'Slash Commands', chip: 'commands/' },
          { id: 'sub', icon: 'users', title: 'Subagents', chip: 'agents/' },
          { id: 'mcp', icon: 'server', title: 'MCP Servers', chip: '.mcp.json' },
          { id: 'hooks', icon: 'zap', title: 'Hooks', chip: 'hooks/hooks.json' },
          { id: 'cfg', icon: 'sliders', title: 'Configuration', chip: 'settings.json' },
        ],
      },
    ],
    edges: [
      { from: 'p', to: 'cmd' },
      { from: 'p', to: 'sub' },
      { from: 'p', to: 'mcp', label: 'bundles' },
      { from: 'p', to: 'hooks' },
      { from: 'p', to: 'cfg' },
    ],
  },
  {
    name: 'plugins-loading',
    block: 23,
    alt: 'Plugin loading process: /plugin install pr-review downloads the manifest from the marketplace, extracts components, configures commands, subagents, MCP servers, and hooks, and reports the plugin installed',
    eyebrow: 'Plugins · Loading',
    title: 'What [[/plugin install]] does',
    sub: 'One command fetches the manifest and wires up every component.',
    layout: 'sequence',
    headW: 168,
    participants: [
      { id: 'user', icon: 'user', title: 'User' },
      { id: 'claude', icon: 'cpu', title: 'Claude Code', accent: true },
      { id: 'mkt', icon: 'globe', title: 'Marketplace' },
      { id: 'inst', icon: 'download', title: 'Installer' },
      { id: 'cmd', icon: 'terminal', title: 'Commands' },
      { id: 'sub', icon: 'users', title: 'Subagents' },
      { id: 'mcp', icon: 'server', title: 'MCP Servers' },
      { id: 'hooks', icon: 'zap', title: 'Hooks' },
      { id: 'tools', icon: 'tool', title: 'Tools' },
    ],
    steps: [
      { from: 'user', to: 'claude', label: '/plugin install pr-review' },
      { from: 'claude', to: 'mkt', label: 'Download plugin manifest' },
      { from: 'mkt', to: 'claude', label: 'Return plugin definition', dashed: true },
      { from: 'claude', to: 'inst', label: 'Extract components' },
      { from: 'inst', to: 'cmd', label: 'Configure' },
      { from: 'inst', to: 'sub', label: 'Configure' },
      { from: 'inst', to: 'mcp', label: 'Configure' },
      { from: 'inst', to: 'hooks', label: 'Configure' },
      { from: 'cmd', to: 'tools', label: 'Ready to use', dashed: true },
      { from: 'sub', to: 'tools', label: 'Ready to use', dashed: true },
      { from: 'mcp', to: 'tools', label: 'Ready to use', dashed: true },
      { from: 'hooks', to: 'tools', label: 'Ready to use', dashed: true },
      { from: 'tools', to: 'claude', label: 'Plugin installed ✓', dashed: true },
    ],
  },
  {
    name: 'plugins-marketplace',
    block: 24,
    alt: 'Plugin marketplace: official Anthropic plugins by category, a community marketplace you can search, and private enterprise registries for internal plugins',
    eyebrow: 'Plugins · Marketplace',
    title: 'Where [[plugins]] come from',
    sub: 'Three sources, each organized its own way.',
    layout: 'graph',
    colgap: 220,
    cardMax: 460,
    rowgap: 18,
    columns: [
      { nodes: [{ id: 'm', icon: 'globe', title: 'Plugin Marketplace', accent: true }] },
      {
        nodes: [
          { id: 'off', icon: 'shield', title: 'Official · Anthropic', chip: 'by category', desc: 'Development · DevOps · Documentation' },
          { id: 'com', icon: 'users', title: 'Community Marketplace', chip: 'search', desc: 'DevOps Automation · Mobile Dev · Data Science' },
          { id: 'ent', icon: 'briefcase', title: 'Enterprise Registry', chip: 'internal', desc: 'Company Standards · Legacy Systems · Compliance' },
        ],
      },
    ],
    edges: [
      { from: 'm', to: 'off' },
      { from: 'm', to: 'com' },
      { from: 'm', to: 'ent' },
    ],
  },
  {
    name: 'plugins-lifecycle',
    block: 25,
    alt: 'Plugin installation and lifecycle: browse the marketplace, view the plugin page, install with /plugin install, configure, and use it; check for updates, or disable and later re-enable it',
    eyebrow: 'Plugins · Lifecycle',
    title: 'Install, use, [[update]]',
    sub: 'A plugin stays in use until you disable it, and can be re-enabled later.',
    layout: 'graph',
    colgap: 120,
    cardMax: 230,
    rowgap: 56,
    dense: true,
    vertical: true,
    columns: [
      { nodes: [{ id: 'a', icon: 'search', title: 'Discover', chip: 'marketplace' }] },
      { nodes: [{ id: 'b', icon: 'eye', title: 'Plugin Page', chip: 'components' }] },
      { nodes: [{ id: 'c', icon: 'download', title: 'Install', chip: '/plugin install' }] },
      { nodes: [{ id: 'd', icon: 'sliders', title: 'Configure', chip: 'extract' }] },
      { nodes: [{ id: 'use', icon: 'play', title: 'Use', chip: 'active', accent: true }] },
      {
        nodes: [
          { id: 'up', icon: 'refresh', title: 'Update' },
          { id: 'dis', icon: 'power', title: 'Disable' },
          { id: 'en', icon: 'zap', title: 'Enable' },
        ],
      },
    ],
    edges: [
      { from: 'a', to: 'b' },
      { from: 'b', to: 'c' },
      { from: 'c', to: 'd' },
      { from: 'd', to: 'use' },
      { from: 'use', to: 'up', label: 'check' },
      { from: 'up', to: 'use', dashed: true },
      { from: 'use', to: 'dis', label: 'done' },
      { from: 'dis', to: 'en', label: 'later' },
      { from: 'en', to: 'use', dashed: true },
    ],
  },
  {
    name: 'plugins-when-to-create',
    block: 26,
    alt: 'When to create a plugin: create one if you need multiple components, need auto configuration, or want to share with the team; otherwise use an individual feature or keep a local setup',
    eyebrow: 'Plugins · Decision',
    title: 'Should you build a [[plugin]]?',
    sub: 'Any one "yes" is reason enough.',
    layout: 'graph',
    colgap: 200,
    cardMax: 340,
    rowgap: 30,
    columns: [
      { nodes: [{ id: 'a', q: true, title: 'Should I create a plugin?' }] },
      {
        nodes: [
          { id: 'b', q: true, title: 'Multiple components?', chip: 'commands, agents, MCPs' },
          { id: 'g', q: true, title: 'Needs auto configuration?', chip: 'complex setup' },
          { id: 'e', q: true, title: 'Share with team?', chip: 'team workflow' },
        ],
      },
      {
        nodes: [
          { id: 'ind', icon: 'grid', title: 'Use Individual Feature' },
          { id: 'yes', icon: 'check', title: 'Create Plugin', accent: true },
          { id: 'loc', icon: 'monitor', title: 'Keep as Local Setup' },
        ],
      },
    ],
    edges: [
      { from: 'a', to: 'b' },
      { from: 'a', to: 'g' },
      { from: 'a', to: 'e' },
      { from: 'b', to: 'ind', dashed: true },
      { from: 'b', to: 'yes' },
      { from: 'g', to: 'ind', dashed: true },
      { from: 'g', to: 'yes' },
      { from: 'e', to: 'yes' },
      { from: 'e', to: 'loc', dashed: true },
    ],
    footer: '<b>Solid line</b> = yes &nbsp;·&nbsp; <b>Dashed line</b> = no',
  },
  {
    name: 'interaction-timeline',
    block: 27,
    alt: 'Interaction timeline: a session loads memory, discovers skills, registers slash commands, and connects MCP servers; then each slash command, skill, MCP query, or subagent delegation uses that memory',
    eyebrow: 'Integration · Session Timeline',
    title: 'What loads when a [[session starts]]',
    sub: 'Everything is ready before your first message, and memory informs every action.',
    layout: 'graph',
    colgap: 64,
    cardMax: 250,
    rowgap: 14,
    dense: true,
    columns: [
      { nodes: [{ id: 'a', icon: 'power', title: 'Session Start' }] },
      { nodes: [{ id: 'b', icon: 'database', title: 'Memory', chip: 'CLAUDE.md' }] },
      { nodes: [{ id: 'c', icon: 'star', title: 'Skills', chip: 'discover' }] },
      { nodes: [{ id: 'd', icon: 'terminal', title: 'Commands', chip: 'register' }] },
      { nodes: [{ id: 'e', icon: 'server', title: 'MCP Servers', chip: 'connect' }] },
      { nodes: [{ id: 'f', icon: 'message', title: 'User Interaction', chip: 'ready', accent: true }] },
      {
        label: 'Each uses memory',
        nodes: [
          { id: 'g', icon: 'terminal', title: 'Slash Command', chip: 'type /cmd' },
          { id: 'h', icon: 'zap', title: 'Skill', chip: 'auto' },
          { id: 'i', icon: 'database', title: 'MCP Data', chip: 'query' },
          { id: 'j', icon: 'users', title: 'Subagent', chip: 'complex' },
        ],
      },
    ],
    edges: [
      { from: 'a', to: 'b' },
      { from: 'b', to: 'c' },
      { from: 'c', to: 'd' },
      { from: 'd', to: 'e' },
      { from: 'e', to: 'f' },
      { from: 'f', to: 'g' },
      { from: 'f', to: 'h' },
      { from: 'f', to: 'i' },
      { from: 'f', to: 'j' },
    ],
  },
  {
    name: 'customer-support-architecture',
    block: 28,
    alt: 'Customer support automation: a support router checks memory and MCP lookups, routes the email to a tech support, billing, or escalation subagent, formats a reply with a response generator skill, then notifies Slack and replies to the customer',
    eyebrow: 'Integration · Example',
    title: 'Automating [[customer support]]',
    sub: 'Memory, MCP, subagents, and skills working on one email.',
    layout: 'graph',
    colgap: 120,
    cardMax: 270,
    rowgap: 30,
    dense: true,
    columns: [
      { label: 'Inbound', nodes: [{ id: 'mail', icon: 'mail', title: 'Customer Email' }] },
      {
        label: 'Router',
        nodes: [
          { id: 'mem', icon: 'database', title: 'Memory', chip: 'history' },
          { id: 'router', icon: 'shuffle', title: 'Support Router' },
          { id: 'look', icon: 'server', title: 'MCP Lookups', chip: 'DB · Slack' },
        ],
      },
      {
        label: 'Subagents',
        nodes: [
          { id: 'tech', icon: 'tool', title: 'Tech Support', chip: 'technical' },
          { id: 'bill', icon: 'briefcase', title: 'Billing', chip: 'payments' },
          { id: 'esc', icon: 'bell', title: 'Escalation', chip: 'priority' },
        ],
      },
      { label: 'Skill', nodes: [{ id: 'skill', icon: 'star', title: 'Response Generator', chip: 'brand voice' }] },
      { label: 'Output', nodes: [{ id: 'out', icon: 'file', title: 'Formatted Response' }] },
      {
        label: 'Delivery',
        nodes: [
          { id: 'slack', icon: 'message', title: 'MCP: Slack', chip: 'notify team' },
          { id: 'reply', icon: 'send', title: 'Customer Reply', accent: true },
        ],
      },
    ],
    edges: [
      { from: 'mail', to: 'router', label: 'receives' },
      { from: 'router', to: 'mem', label: 'analyze' },
      { from: 'router', to: 'look', label: 'lookup' },
      { from: 'router', to: 'tech', label: 'complex' },
      { from: 'router', to: 'bill', label: 'simple' },
      { from: 'router', to: 'esc', label: 'urgent' },
      { from: 'tech', to: 'skill' },
      { from: 'bill', to: 'skill', label: 'format' },
      { from: 'esc', to: 'skill' },
      { from: 'skill', to: 'out' },
      { from: 'out', to: 'slack', label: 'post' },
      { from: 'out', to: 'reply', label: 'send' },
    ],
  },
  {
    name: 'feature-orchestration',
    block: 29,
    alt: 'Complete feature orchestration: to build an auth system, Claude Code loads standards from memory, queries GitHub over MCP, detects security and testing skills, delegates implementation and testing to subagents, and delivers the result',
    eyebrow: 'Integration · Orchestration',
    title: 'Every feature, [[one request]]',
    sub: 'How memory, MCP, skills, and subagents combine to build an auth system.',
    layout: 'sequence',
    rowH: 50,
    participants: [
      { id: 'user', icon: 'user', title: 'User' },
      { id: 'claude', icon: 'cpu', title: 'Claude Code', accent: true },
      { id: 'mem', icon: 'database', title: 'Memory', chip: 'CLAUDE.md' },
      { id: 'mcp', icon: 'server', title: 'MCP Servers' },
      { id: 'skills', icon: 'star', title: 'Skills' },
      { id: 'sub', icon: 'users', title: 'Subagents' },
    ],
    steps: [
      { from: 'user', to: 'claude', label: '"Build auth system"' },
      { from: 'claude', to: 'mem', label: 'Load project standards' },
      { from: 'mem', to: 'claude', label: 'Auth standards, team practices', dashed: true },
      { from: 'claude', to: 'mcp', label: 'Query GitHub for similar implementations' },
      { from: 'mcp', to: 'claude', label: 'Code examples, best practices', dashed: true },
      { from: 'claude', to: 'skills', label: 'Detect matching skills' },
      { from: 'skills', to: 'claude', label: 'Security Review + Testing skills', dashed: true },
      { from: 'claude', to: 'sub', label: 'Delegate implementation' },
      { from: 'sub', to: 'sub', label: 'Build feature' },
      { from: 'claude', to: 'skills', label: 'Apply Security Review skill' },
      { from: 'skills', to: 'claude', label: 'Security checklist results', dashed: true },
      { from: 'claude', to: 'sub', label: 'Delegate testing' },
      { from: 'sub', to: 'claude', label: 'Test results', dashed: true },
      { from: 'claude', to: 'user', label: 'Complete system delivered' },
    ],
  },
  {
    name: 'when-to-use-each-feature',
    block: 30,
    alt: 'When to use each feature: a slash command for repeated workflows, MCP for real-time data, memory for things to remember next time, a subagent for specialized subtasks, and a skill for domain-specific work',
    eyebrow: 'Integration · Choosing',
    title: 'Pick the feature by [[task type]]',
    sub: 'Match what the task needs to the feature built for it.',
    layout: 'graph',
    colgap: 170,
    cardMax: 380,
    rowgap: 14,
    columns: [
      { nodes: [{ id: 'a', icon: 'inbox', title: 'New Task' }] },
      { nodes: [{ id: 'b', q: true, title: 'Type of task?' }] },
      {
        nodes: [
          { id: 'c', icon: 'terminal', title: 'Slash Command', chip: 'repeated workflow', desc: '✓ Team shortcut' },
          { id: 'd', icon: 'server', title: 'MCP Protocol', chip: 'need real-time data', desc: '✓ Live API access' },
          { id: 'e', icon: 'database', title: 'Memory', chip: 'remember for next time', desc: '✓ Persistent context' },
          { id: 'f', icon: 'users', title: 'Subagent', chip: 'specialized subtask', desc: '✓ Parallel execution' },
          { id: 'g', icon: 'star', title: 'Skill', chip: 'domain-specific work', desc: '✓ Auto-invoked expertise' },
        ],
      },
    ],
    edges: [
      { from: 'a', to: 'b' },
      { from: 'b', to: 'c' },
      { from: 'b', to: 'd' },
      { from: 'b', to: 'e' },
      { from: 'b', to: 'f' },
      { from: 'b', to: 'g' },
    ],
  },
  {
    name: 'selection-decision-tree',
    block: 31,
    alt: 'Selection decision tree: quick repeated tasks use a slash command or skill; external data uses MCP or memory; complex projects use subagents or skills with memory; long-term context uses memory; team workflows use slash commands with memory; full automation combines skills, subagents, and MCP',
    eyebrow: 'Integration · Decision Tree',
    title: 'Need to [[extend Claude]]?',
    sub: 'Start from your situation and follow the branch.',
    layout: 'graph',
    colgap: 190,
    cardMax: 330,
    rowgap: 12,
    dense: true,
    columns: [
      { nodes: [{ id: 'start', q: true, title: 'Need to extend Claude?' }] },
      {
        label: 'Situation',
        nodes: [
          { id: 's1', icon: 'zap', title: 'Quick repeated task', chip: 'manual or auto?' },
          { id: 's2', icon: 'globe', title: 'Need external data', chip: 'real-time?' },
          { id: 's3', icon: 'layers', title: 'Complex project', chip: 'multiple roles?' },
          { id: 's4', icon: 'clock', title: 'Long-term context' },
          { id: 's5', icon: 'users', title: 'Team workflow' },
          { id: 's6', icon: 'play', title: 'Full automation' },
        ],
      },
      {
        label: 'Use',
        nodes: [
          { id: 'o1', icon: 'terminal', title: 'Slash Command' },
          { id: 'o2', icon: 'star', title: 'Skill' },
          { id: 'o3', icon: 'server', title: 'MCP Protocol' },
          { id: 'o4', icon: 'database', title: 'Memory' },
          { id: 'o5', icon: 'users', title: 'Subagents' },
          { id: 'o6', icon: 'layers', title: 'Skills + Memory' },
          { id: 'o7', icon: 'database', title: 'Memory' },
          { id: 'o8', icon: 'terminal', title: 'Slash Command + Memory' },
          { id: 'o9', icon: 'zap', title: 'Skills + Subagents + MCP', accent: true },
        ],
      },
    ],
    edges: [
      { from: 'start', to: 's1' },
      { from: 'start', to: 's2' },
      { from: 'start', to: 's3' },
      { from: 'start', to: 's4' },
      { from: 'start', to: 's5' },
      { from: 'start', to: 's6' },
      { from: 's1', to: 'o1', label: 'manual' },
      { from: 's1', to: 'o2', label: 'auto' },
      { from: 's2', to: 'o3', label: 'yes' },
      { from: 's2', to: 'o4', label: 'no' },
      { from: 's3', to: 'o5', label: 'yes' },
      { from: 's3', to: 'o6', label: 'no' },
      { from: 's4', to: 'o7' },
      { from: 's5', to: 'o8' },
      { from: 's6', to: 'o9' },
    ],
  },
  {
    name: 'command-precedence',
    alt: 'Slash command precedence: for a short name like /deploy, Claude Code checks enterprise, then personal, then project skills; your skill replaces a bundled command; plugin and claude.ai synced skills get the short name only if it is still free. At every level a skill beats a .claude/commands file of the same name',
    eyebrow: 'Slash Commands & Skills · Precedence',
    title: 'Who wins [[/deploy]]?',
    sub: 'Claude Code checks each source in order. The first one that defines the name runs.',
    layout: 'graph',
    colgap: 34,
    cardMax: 250,
    dense: true,
    vertical: true,
    columns: [
      { label: 'Wins first', nodes: [{ id: 'ent', icon: 'shield', title: 'Enterprise', chip: 'managed settings', desc: 'Deployed by your org’s admins', num: '1', accent: true }] },
      { nodes: [{ id: 'per', icon: 'user', title: 'Personal', chip: '~/.claude/skills/', desc: 'Yours, in every project', num: '2' }] },
      { nodes: [{ id: 'proj', icon: 'folder', title: 'Project', chip: '.claude/skills/', desc: 'Plus parent folders to repo root', num: '3' }] },
      { nodes: [{ id: 'bun', icon: 'package', title: 'Bundled', chip: '/code-review', desc: 'Any of yours replaces it', num: '4' }] },
      { label: 'Only if name is free', nodes: [{ id: 'free', icon: 'link', title: 'Plugin · claude.ai', chip: 'short name', desc: 'Full name always works', num: '5' }] },
    ],
    edges: [
      { from: 'ent', to: 'per' },
      { from: 'per', to: 'proj' },
      { from: 'proj', to: 'bun' },
      { from: 'bun', to: 'free' },
    ],
    footer: '<b>Same level?</b> A skill beats a <code>.claude/commands/</code> file &nbsp;·&nbsp; <b>Prefixed names</b> like <code>/my-plugin:deploy</code> skip the ladder',
  },
  {
    name: 'command-naming',
    alt: 'How Claude Code names slash commands: a command file uses its file name, subfolders become colon prefixes, a skill uses its name field or folder name, a clashing nested skill gets its path as a prefix, plugin skills get the plugin prefix, and claude.ai synced skills get the anthropic-skills prefix',
    eyebrow: 'Slash Commands & Skills · Naming',
    title: 'How a file becomes a [[/name]]',
    sub: 'Where a file lives decides the command you type. Prefixes keep the names apart.',
    layout: 'graph',
    colgap: 230,
    cardMax: 470,
    rowgap: 14,
    dense: true,
    columns: [
      {
        label: 'File',
        nodes: [
          { id: 'f1', icon: 'file', title: 'Command file', chip: '.claude/commands/deploy.md' },
          { id: 'f2', icon: 'folder', title: 'Command in a subfolder', chip: '.claude/commands/frontend/component.md' },
          { id: 'f3', icon: 'star', title: 'Skill', chip: '.claude/skills/deploy-staging/SKILL.md' },
          { id: 'f4', icon: 'layers', title: 'Nested skill (name clash)', chip: 'apps/web/.claude/skills/deploy/SKILL.md' },
          { id: 'f5', icon: 'package', title: 'Plugin skill', chip: 'my-plugin/skills/review/SKILL.md' },
          { id: 'f6', icon: 'globe', title: 'claude.ai account skill', chip: 'deploy' },
        ],
      },
      {
        label: 'You type',
        nodes: [
          { id: 'n1', icon: 'terminal', title: '/deploy' },
          { id: 'n2', icon: 'terminal', title: '/frontend:component' },
          { id: 'n3', icon: 'terminal', title: '/deploy-staging', desc: 'or its name: field' },
          { id: 'n4', icon: 'terminal', title: '/apps/web:deploy', desc: 'root one keeps /deploy' },
          { id: 'n5', icon: 'terminal', title: '/my-plugin:review', desc: '/review too, if free' },
          { id: 'n6', icon: 'terminal', title: '/anthropic-skills:deploy', desc: '/deploy too, if free' },
        ],
      },
    ],
    edges: [
      { from: 'f1', to: 'n1', label: 'file name' },
      { from: 'f2', to: 'n2', label: 'folder → :' },
      { from: 'f3', to: 'n3', label: 'folder name' },
      { from: 'f4', to: 'n4', label: 'path prefix' },
      { from: 'f5', to: 'n5', label: 'plugin prefix' },
      { from: 'f6', to: 'n6', label: 'synced' },
    ],
  },
  {
    name: 'learning-path',
    doc: 'ja/LEARNING-ROADMAP.md',
    block: 1,
    alt: 'Learning path: take the self-assessment quiz to find your level, then work through milestones A and B at each level, moving up from Level 1 to Level 3',
    eyebrow: 'Learning Roadmap · Your Path',
    title: 'Your [[learning path]]',
    sub: 'Take the quiz to find your level, then work through each milestone in order.',
    layout: 'graph',
    colgap: 150,
    cardMax: 340,
    rowgap: 64,
    columns: [
      { nodes: [{ id: 'q', icon: 'target', title: 'Self-Assessment Quiz', desc: 'Find your level', accent: true }] },
      {
        label: 'Level',
        nodes: [
          { id: 'l1', icon: 'play', title: 'Level 1: Beginner', chip: '~3 hours', desc: 'Getting started' },
          { id: 'l2', icon: 'layers', title: 'Level 2: Intermediate', chip: '~5 hours', desc: 'Building workflows' },
          { id: 'l3', icon: 'zap', title: 'Level 3: Advanced', chip: '~5 hours', desc: 'Power user' },
        ],
      },
      {
        label: 'Milestone A',
        nodes: [
          { id: 'a1', icon: 'terminal', num: '1A', title: 'First Commands', desc: 'Slash commands + memory' },
          { id: 'a2', icon: 'zap', num: '2A', title: 'Automation', desc: 'Skills + hooks' },
          { id: 'a3', icon: 'sliders', num: '3A', title: 'Advanced Features', desc: 'Planning + permissions' },
        ],
      },
      {
        label: 'Milestone B',
        nodes: [
          { id: 'b1', icon: 'shield', num: '1B', title: 'Safe Exploration', desc: 'Checkpoints + CLI basics' },
          { id: 'b2', icon: 'link', num: '2B', title: 'Integration', desc: 'MCP + subagents' },
          { id: 'b3', icon: 'package', num: '3B', title: 'Team & Distribution', desc: 'Plugins + CLI mastery' },
        ],
      },
    ],
    edges: [
      { from: 'q', to: 'l1', label: '0–2 checks' },
      { from: 'q', to: 'l2', label: '3–5 checks' },
      { from: 'q', to: 'l3', label: '6–8 checks' },
      { from: 'l1', to: 'l2', label: 'next' },
      { from: 'l2', to: 'l3', label: 'next' },
      { from: 'l1', to: 'a1' },
      { from: 'l2', to: 'a2' },
      { from: 'l3', to: 'a3' },
      { from: 'a1', to: 'b1' },
      { from: 'a2', to: 'b2' },
      { from: 'a3', to: 'b3' },
    ],
    footer: '<b>Total time</b> about 11–13 hours &nbsp;·&nbsp; <b>Quiz</b> your number of checks picks your level',
  },
  {
    name: 'lesson-quiz-flow',
    alt: 'Lesson quiz flow: select a lesson, choose when to take it (before, during, or after), answer 10 questions in 5 rounds, then get your score and feedback',
    eyebrow: 'Skill · /lesson-quiz',
    title: 'How the [[lesson quiz]] works',
    sub: 'Ten questions on one lesson, scored with feedback.',
    layout: 'graph',
    colgap: 110,
    cardMax: 300,
    columns: [
      { nodes: [{ id: 'a', icon: 'book', num: '01', title: 'Select a lesson', chip: '/lesson-quiz hooks' }] },
      { nodes: [{ id: 'b', icon: 'clock', num: '02', title: 'Choose timing', chip: 'pre · during · after' }] },
      { nodes: [{ id: 'c', icon: 'list', num: '03', title: 'Answer questions', chip: '10 in 5 rounds' }] },
      { nodes: [{ id: 'd', icon: 'chart', num: '04', title: 'Score & feedback', chip: 'review weak spots', accent: true }] },
    ],
    edges: [{ from: 'a', to: 'b' }, { from: 'b', to: 'c' }, { from: 'c', to: 'd' }],
  },
  {
    name: 'self-assessment-flow',
    alt: 'Self-assessment flow: choose an assessment mode, answer quiz questions, get per-topic scores, get a personalized learning path, then start learning or dive deeper',
    eyebrow: 'Skill · /self-assessment',
    title: 'Find your level, [[get a path]]',
    sub: 'A quiz across all feature areas that ends in a personal learning plan.',
    layout: 'graph',
    colgap: 80,
    cardMax: 270,
    dense: true,
    vertical: true,
    columns: [
      { nodes: [{ id: 'a', icon: 'sliders', num: '01', title: 'Choose mode', chip: 'quick or deep' }] },
      { nodes: [{ id: 'b', icon: 'list', num: '02', title: 'Answer quiz', chip: 'questions' }] },
      { nodes: [{ id: 'c', icon: 'chart', num: '03', title: 'Topic scores', chip: 'per topic' }] },
      { nodes: [{ id: 'd', icon: 'target', num: '04', title: 'Learning path', chip: 'personalized' }] },
      { nodes: [{ id: 'e', icon: 'play', num: '05', title: 'Start learning', chip: 'or deep dive', accent: true }] },
    ],
    edges: [{ from: 'a', to: 'b' }, { from: 'b', to: 'c' }, { from: 'c', to: 'd' }, { from: 'd', to: 'e' }],
  },
  {
    name: 'style-guide-example',
    alt: 'Style guide example diagram: component A connects to component B, which connects to component C',
    eyebrow: 'Style Guide · Mermaid Example',
    title: 'A simple [[component flow]]',
    sub: 'The example diagram from the style guide.',
    layout: 'graph',
    colgap: 160,
    cardMax: 300,
    columns: [
      { nodes: [{ id: 'a', icon: 'grid', title: 'Component A' }] },
      { nodes: [{ id: 'b', icon: 'grid', title: 'Component B' }] },
      { nodes: [{ id: 'c', icon: 'grid', title: 'Component C', accent: true }] },
    ],
    edges: [{ from: 'a', to: 'b' }, { from: 'b', to: 'c' }],
  },
  {
    name: 'style-guide-basic',
    alt: 'Style guide example diagram: a start step that leads to an end step',
    eyebrow: 'Style Guide · Mermaid Example',
    title: 'From [[start]] to end',
    sub: 'The simplest example diagram from the style guide.',
    layout: 'graph',
    colgap: 200,
    cardMax: 300,
    columns: [
      { nodes: [{ id: 'a', icon: 'play', title: 'Start' }] },
      { nodes: [{ id: 'b', icon: 'check', title: 'End', accent: true }] },
    ],
    edges: [{ from: 'a', to: 'b' }],
  },
  {
    name: 'slash-command-resolution',
    alt: 'How a slash command runs: Claude Code checks whether it is built-in, a skill, a plugin command, or an MCP prompt; a skill is loaded, its frontmatter parsed, variables substituted, shell commands run, and the result sent to Claude',
    eyebrow: 'Slash Commands · How They Run',
    title: 'What happens after you type [[/command]]',
    sub: 'Claude Code works out the command type, then runs it.',
    layout: 'graph',
    colgap: 70,
    cardMax: 220,
    rowgap: 14,
    dense: true,
    vertical: true,
    columns: [
      { nodes: [{ id: 'a', icon: 'terminal', title: 'User Input', chip: '/name' }] },
      { nodes: [{ id: 'b', q: true, title: 'Type?' }] },
      {
        nodes: [
          { id: 'c', icon: 'zap', title: 'Built-in', chip: 'runs' },
          { id: 'd', icon: 'file', title: 'Skill', chip: 'SKILL.md' },
          { id: 'e', icon: 'package', title: 'Plugin', chip: 'command' },
          { id: 'f', icon: 'server', title: 'MCP', chip: 'prompt' },
        ],
      },
      { nodes: [{ id: 'g', icon: 'list', title: 'Parse', chip: 'frontmatter' }] },
      { nodes: [{ id: 'h', icon: 'edit', title: 'Substitute', chip: 'variables' }] },
      { nodes: [{ id: 'i', icon: 'terminal', title: 'Run shell', chip: 'commands' }] },
      { nodes: [{ id: 'j', icon: 'send', title: 'To Claude', chip: 'results', accent: true }] },
    ],
    edges: [
      { from: 'a', to: 'b' },
      { from: 'b', to: 'c' },
      { from: 'b', to: 'd' },
      { from: 'b', to: 'e' },
      { from: 'b', to: 'f' },
      { from: 'd', to: 'g' },
      { from: 'g', to: 'h' },
      { from: 'h', to: 'i' },
      { from: 'i', to: 'j' },
    ],
    footer: 'The skill path is shown in detail; built-in, plugin, and MCP commands run their own way.',
  },
  {
    name: 'slash-command-execution',
    alt: 'Slash command execution: the user types /optimize, Claude Code finds optimize/SKILL.md, parses its frontmatter, runs any shell substitutions, fills in $ARGUMENTS, and returns results',
    eyebrow: 'Slash Commands · Execution',
    title: 'Running [[/optimize]], step by step',
    sub: 'How a skill-based command is found, filled in, and run.',
    layout: 'sequence',
    participants: [
      { id: 'user', icon: 'user', title: 'User' },
      { id: 'claude', icon: 'cpu', title: 'Claude Code', accent: true },
      { id: 'fs', icon: 'folder', title: 'File System' },
      { id: 'cli', icon: 'terminal', title: 'Shell / Bash' },
    ],
    steps: [
      { from: 'user', to: 'claude', label: 'Types /optimize' },
      { from: 'claude', to: 'fs', label: 'Searches .claude/skills/ and .claude/commands/' },
      { from: 'fs', to: 'claude', label: 'Returns optimize/SKILL.md', dashed: true },
      { from: 'claude', to: 'claude', label: 'Parses frontmatter' },
      { from: 'claude', to: 'cli', label: 'Runs !`command` substitutions' },
      { from: 'cli', to: 'claude', label: 'Command outputs', dashed: true },
      { from: 'claude', to: 'claude', label: 'Fills in $ARGUMENTS' },
      { from: 'claude', to: 'user', label: 'Processes prompt' },
      { from: 'claude', to: 'user', label: 'Returns results' },
    ],
  },
  {
    name: 'memory-loading',
    alt: 'How memory loads: at session start Claude Code loads your CLAUDE.md files in full and the auto memory index MEMORY.md; during the session, corrections are written to auto memory and "add this to CLAUDE.md" updates your files',
    eyebrow: 'Memory · Two Kinds',
    title: 'What you write, [[what Claude writes]]',
    sub: 'CLAUDE.md files and auto memory both load at the start of every session.',
    layout: 'graph',
    colgap: 150,
    cardMax: 320,
    rowgap: 40,
    columns: [
      {
        label: 'Memory',
        nodes: [
          { id: 'b', icon: 'file', title: 'CLAUDE.md Files', chip: 'you write' },
          { id: 'c', icon: 'zap', title: 'Auto Memory', chip: 'Claude writes' },
        ],
      },
      { label: 'Start', nodes: [{ id: 'a', icon: 'power', title: 'Session Start' }] },
      { label: 'Session', nodes: [{ id: 'd', icon: 'message', title: 'Claude Session', accent: true }] },
      { label: 'You', nodes: [{ id: 'e', icon: 'user', title: 'Your Correction', chip: 'or preference' }] },
    ],
    edges: [
      { from: 'b', to: 'a', label: 'loaded in full' },
      { from: 'c', to: 'a', label: 'MEMORY.md loaded' },
      { from: 'a', to: 'd' },
      { from: 'd', to: 'e', label: 'remember that…' },
      { from: 'e', to: 'c', label: 'written during session', dashed: true },
      { from: 'd', to: 'b', label: 'add this to CLAUDE.md', dashed: true },
    ],
  },
  {
    name: 'memory-import-hierarchy',
    alt: 'CLAUDE.md load order: managed policy loads first, then user instructions, project instructions, and local instructions; project instructions can import other files such as docs/architecture.md, which can import docs/api-standards.md',
    eyebrow: 'Memory · Load Order & Imports',
    title: 'How [[CLAUDE.md]] files stack up',
    sub: 'Four levels load in order, and any file can pull in others with @imports.',
    layout: 'graph',
    colgap: 90,
    cardMax: 300,
    rowgap: 40,
    dense: true,
    columns: [
      { nodes: [{ id: 'a', icon: 'shield', num: '1', title: 'Managed Policy', chip: '…/ClaudeCode/CLAUDE.md' }] },
      { nodes: [{ id: 'b', icon: 'user', num: '2', title: 'User', chip: '~/.claude/CLAUDE.md' }] },
      {
        nodes: [
          { id: 'c', icon: 'folder', num: '3', title: 'Project', chip: './CLAUDE.md', accent: true },
          { id: 'h', icon: 'link', title: 'Import', chip: '@docs/architecture.md' },
        ],
      },
      {
        nodes: [
          { id: 'd', icon: 'monitor', num: '4', title: 'Local', chip: './CLAUDE.local.md' },
          { id: 'i', icon: 'link', title: 'Import', chip: '@docs/api-standards.md' },
        ],
      },
    ],
    edges: [
      { from: 'a', to: 'b', label: 'loads first' },
      { from: 'b', to: 'c' },
      { from: 'c', to: 'd' },
      { from: 'c', to: 'h', label: 'imports' },
      { from: 'h', to: 'i', label: 'imports' },
    ],
    footer: '<b>Project</b> can also live at <code>./.claude/CLAUDE.md</code>',
  },
  {
    name: 'auto-memory',
    alt: 'Auto memory: at session start Claude loads the first 200 lines or 25KB of MEMORY.md; during the session it writes general notes to MEMORY.md and topic notes to files like debugging.md, and loads topic files on demand',
    eyebrow: 'Memory · Auto Memory',
    title: 'How [[auto memory]] works',
    sub: 'Claude keeps its own notes, loading the index up front and topic files when needed.',
    layout: 'graph',
    colgap: 70,
    cardMax: 300,
    rowgap: 26,
    dense: true,
    columns: [
      { nodes: [{ id: 'a', icon: 'power', title: 'Session Starts' }] },
      { nodes: [{ id: 'b', icon: 'file', title: 'Load MEMORY.md', chip: '200 lines · 25KB' }] },
      { nodes: [{ id: 'c', icon: 'message', title: 'Session Active', accent: true }, { id: 'i', icon: 'download', title: 'Load Topic Files', chip: 'on demand' }] },
      { nodes: [{ id: 'd', icon: 'search', title: 'Finds Patterns', chip: '& insights' }] },
      { nodes: [{ id: 'e', q: true, title: 'Write to auto memory' }] },
      {
        nodes: [
          { id: 'f', icon: 'file', title: 'MEMORY.md', chip: 'general notes' },
          { id: 'g', icon: 'file', title: 'debugging.md', chip: 'topic' },
          { id: 'h', icon: 'file', title: 'api‑conventions.md', chip: 'topic' },
        ],
      },
    ],
    edges: [
      { from: 'a', to: 'b' },
      { from: 'b', to: 'c' },
      { from: 'c', to: 'd' },
      { from: 'd', to: 'e' },
      { from: 'e', to: 'f' },
      { from: 'e', to: 'g' },
      { from: 'e', to: 'h' },
      { from: 'c', to: 'i' },
      { from: 'i', to: 'c' },
    ],
  },
  {
    name: 'memory-hierarchy-imports',
    alt: 'Memory hierarchy with imports: managed policy has the highest priority, followed by managed drop-ins, project memory, project rules, user memory, user rules, local project memory, and auto memory; project memory can import docs/architecture.md, which imports docs/api-standards.md',
    eyebrow: 'Memory · Hierarchy',
    title: 'Eight levels, [[highest priority first]]',
    sub: 'Each level loads in order, and project memory can import other files.',
    layout: 'graph',
    colgap: 30,
    cardMax: 200,
    rowgap: 44,
    dense: true,
    vertical: true,
    columns: [
      { label: 'Highest', nodes: [{ id: 'a', icon: 'shield', num: '1', title: 'Managed Policy', chip: 'admin', accent: true }] },
      { nodes: [{ id: 'a2', icon: 'layers', num: '2', title: 'Managed Drop-ins', chip: 'settings.d/' }] },
      { nodes: [{ id: 'b', icon: 'file', num: '3', title: 'Project Memory', chip: './CLAUDE.md' }, { id: 'h', icon: 'link', title: 'Import', chip: 'architecture.md' }, { id: 'i', icon: 'link', title: 'Import', chip: 'api-standards.md' }] },
      { nodes: [{ id: 'c', icon: 'list', num: '4', title: 'Project Rules', chip: '.claude/rules/' }] },
      { nodes: [{ id: 'd', icon: 'user', num: '5', title: 'User Memory', chip: '~/.claude/' }] },
      { nodes: [{ id: 'e', icon: 'list', num: '6', title: 'User Rules', chip: '~/.claude/rules/' }] },
      { nodes: [{ id: 'f', icon: 'monitor', num: '7', title: 'Local Memory', chip: 'CLAUDE.local.md' }] },
      { label: 'Lowest', nodes: [{ id: 'g', icon: 'zap', num: '8', title: 'Auto Memory', chip: 'memory/' }] },
    ],
    edges: [
      { from: 'a', to: 'a2' },
      { from: 'a2', to: 'b' },
      { from: 'b', to: 'c' },
      { from: 'c', to: 'd' },
      { from: 'd', to: 'e' },
      { from: 'e', to: 'f' },
      { from: 'f', to: 'g' },
      { from: 'b', to: 'h', label: 'imports' },
      { from: 'h', to: 'i', label: 'imports' },
    ],
  },
  {
    name: 'skills-progressive-disclosure',
    alt: 'Skill progressive disclosure: level 1 metadata (name and description, about 100 tokens per skill) is always loaded; level 2 instructions (the SKILL.md body, under 5k tokens) load when the skill is triggered; level 3 resources (scripts, templates, docs) load only as needed',
    eyebrow: 'Skills · Progressive Disclosure',
    title: 'Three levels, [[loaded only when needed]]',
    sub: 'Claude reads a little about every skill, and the rest only when it uses one.',
    layout: 'graph',
    colgap: 150,
    cardMax: 400,
    columns: [
      { label: 'Always loaded', nodes: [{ id: 'a', icon: 'list', num: '1', title: 'Metadata', chip: 'YAML frontmatter', desc: 'name + description · about 100 tokens per skill' }] },
      { label: 'When triggered', nodes: [{ id: 'b', icon: 'file', num: '2', title: 'Instructions', chip: 'SKILL.md body', desc: 'Workflows & guidance · under 5k tokens', accent: true }] },
      { label: 'As needed', nodes: [{ id: 'c', icon: 'folder', num: '3', title: 'Resources', chip: 'bundled files', desc: 'Scripts, templates, docs · effectively unlimited' }] },
    ],
    edges: [{ from: 'a', to: 'b' }, { from: 'b', to: 'c' }],
  },
  {
    name: 'skills-progressive-loading',
    alt: 'Skill loading in practice: for a security review request, Claude matches the request against skill descriptions loaded at startup, reads the code-review-specialist SKILL.md, then reads a checklist template only when it needs it, and returns the review',
    eyebrow: 'Skills · Loading in Practice',
    title: 'A skill loads [[one level at a time]]',
    sub: 'Instructions and templates are read only once Claude knows it needs them.',
    layout: 'sequence',
    rowH: 50,
    participants: [
      { id: 'user', icon: 'user', title: 'User' },
      { id: 'claude', icon: 'cpu', title: 'Claude', accent: true },
      { id: 'sys', icon: 'grid', title: 'System' },
      { id: 'inst', icon: 'file', title: 'Instructions', chip: 'level 2' },
      { id: 'res', icon: 'folder', title: 'Resources', chip: 'level 3' },
    ],
    steps: [
      { from: 'user', to: 'claude', label: '"Review this code for security issues"' },
      { from: 'claude', to: 'sys', label: 'Check available skills (metadata)' },
      { from: 'sys', to: 'claude', label: 'Descriptions loaded at startup', dashed: true },
      { from: 'claude', to: 'claude', label: 'Match request to a skill' },
      { from: 'claude', to: 'inst', label: 'Read code-review-specialist/SKILL.md' },
      { from: 'inst', to: 'claude', label: 'Level 2: instructions loaded', dashed: true },
      { from: 'claude', to: 'claude', label: 'Need templates?' },
      { from: 'claude', to: 'res', label: 'Read templates/checklist.md' },
      { from: 'res', to: 'claude', label: 'Level 3: template loaded', dashed: true },
      { from: 'claude', to: 'claude', label: 'Follow skill instructions' },
      { from: 'claude', to: 'user', label: 'Full code review' },
    ],
  },
  {
    name: 'skills-loading-basic',
    alt: 'Skill loading: for a security review request, Claude checks skill descriptions loaded at startup, reads code-review/SKILL.md, reads a checklist template if needed, and returns the review',
    eyebrow: 'Skills · Loading',
    title: 'How Claude [[uses a skill]]',
    sub: 'Match the request, read the skill, then read extra files only if needed.',
    layout: 'sequence',
    participants: [
      { id: 'user', icon: 'user', title: 'User' },
      { id: 'claude', icon: 'cpu', title: 'Claude', accent: true },
      { id: 'sys', icon: 'grid', title: 'System' },
      { id: 'skill', icon: 'zap', title: 'Skill' },
    ],
    steps: [
      { from: 'user', to: 'claude', label: '"Review this code for security issues"' },
      { from: 'claude', to: 'sys', label: 'Check available skills (metadata)' },
      { from: 'sys', to: 'claude', label: 'Descriptions loaded at startup', dashed: true },
      { from: 'claude', to: 'claude', label: 'Match request to a skill' },
      { from: 'claude', to: 'skill', label: 'Read code-review/SKILL.md' },
      { from: 'skill', to: 'claude', label: 'Instructions loaded', dashed: true },
      { from: 'claude', to: 'claude', label: 'Need templates?' },
      { from: 'claude', to: 'skill', label: 'Read templates/checklist.md' },
      { from: 'skill', to: 'claude', label: 'Template loaded', dashed: true },
      { from: 'claude', to: 'claude', label: 'Follow skill instructions' },
      { from: 'claude', to: 'user', label: 'Full code review' },
    ],
  },
  {
    name: 'subagent-persistent-memory',
    alt: 'Subagent persistent memory: each subagent session writes to and loads from a shared MEMORY.md, so what one session learns carries over to the next',
    eyebrow: 'Subagents · Persistent Memory',
    title: 'Subagents that [[remember]]',
    sub: 'A shared MEMORY.md carries what each session learned into the next one.',
    layout: 'graph',
    colgap: 170,
    cardMax: 320,
    rowgap: 60,
    columns: [
      { nodes: [{ id: 'a', icon: 'cpu', num: '1', title: 'Subagent Session 1' }] },
      { nodes: [{ id: 'm', icon: 'database', title: 'MEMORY.md', chip: 'persistent', accent: true }] },
      { nodes: [{ id: 'b', icon: 'cpu', num: '2', title: 'Subagent Session 2' }, { id: 'c', icon: 'cpu', num: '3', title: 'Subagent Session 3' }] },
    ],
    edges: [
      { from: 'a', to: 'm', label: 'writes' },
      { from: 'm', to: 'b', label: 'loads into' },
      { from: 'm', to: 'c', label: 'loads into' },
    ],
    footer: 'Each session also <b>updates</b> MEMORY.md, so later sessions start with more.',
  },
  {
    name: 'subagent-worktree-isolation',
    alt: 'Subagent worktree isolation: the main working tree spawns a subagent in its own git worktree and branch; if it makes no changes the worktree is cleaned up automatically, otherwise its path and branch are returned',
    eyebrow: 'Subagents · Worktree Isolation',
    title: 'Changes in a [[separate worktree]]',
    sub: 'The subagent works on its own branch, so your working tree stays untouched.',
    layout: 'graph',
    colgap: 130,
    cardMax: 320,
    rowgap: 40,
    columns: [
      { nodes: [{ id: 'main', icon: 'folder', title: 'Main Working Tree' }] },
      { nodes: [{ id: 'sub', icon: 'cpu', title: 'Subagent', chip: 'isolated worktree' }] },
      { nodes: [{ id: 'wt', icon: 'git', title: 'Git Worktree', chip: 'separate branch', accent: true }] },
      { nodes: [{ id: 'clean', icon: 'refresh', title: 'Auto-cleaned', chip: 'no changes' }, { id: 'ret', icon: 'send', title: 'Path & Branch Returned', chip: 'has changes' }] },
    ],
    edges: [
      { from: 'main', to: 'sub', label: 'spawns' },
      { from: 'sub', to: 'wt', label: 'works in' },
      { from: 'wt', to: 'clean' },
      { from: 'wt', to: 'ret' },
    ],
  },
  {
    name: 'agent-teams',
    alt: 'Agent teams: a team lead assigns work through a shared task list and sends messages through a mailbox; each teammate has its own context, picks up tasks, updates their status, and reads and writes the mailbox',
    eyebrow: 'Subagents · Agent Teams',
    title: 'A lead, a task list, [[a team]]',
    sub: 'Teammates pick up shared tasks and talk through a mailbox, each in its own context.',
    layout: 'graph',
    colgap: 200,
    cardMax: 320,
    rowgap: 40,
    columns: [
      { label: 'Lead', nodes: [{ id: 'lead', icon: 'target', title: 'Team Lead', chip: 'coordinator', accent: true }] },
      {
        label: 'Shared',
        nodes: [
          { id: 'tasks', icon: 'list', title: 'Shared Task List', chip: 'with dependencies' },
          { id: 'mail', icon: 'mail', title: 'Mailbox', chip: 'messages' },
        ],
      },
      {
        label: 'Teammates',
        nodes: [
          { id: 't1', icon: 'cpu', title: 'Teammate 1', chip: 'own context' },
          { id: 't2', icon: 'cpu', title: 'Teammate 2', chip: 'own context' },
          { id: 't3', icon: 'cpu', title: 'Teammate 3', chip: 'own context' },
        ],
      },
    ],
    edges: [
      { from: 'lead', to: 'tasks', label: 'assigns tasks' },
      { from: 'lead', to: 'mail', label: 'sends messages' },
      { from: 'tasks', to: 't1' },
      { from: 'tasks', to: 't2', label: 'picks up work' },
      { from: 'tasks', to: 't3' },
    ],
    footer: 'Teammates also <b>read and write</b> the mailbox and <b>update</b> task status on the shared list.',
  },
  {
    name: 'subagents-integration',
    alt: 'How subagents fit with other features: the main agent uses memory, queries MCP, invokes skills, and delegates to subagents; subagents also use memory and MCP but work in their own clean context window',
    eyebrow: 'Subagents · With Other Features',
    title: 'Where [[subagents]] fit',
    sub: 'The main agent reaches every feature; subagents share memory and MCP but keep a clean context.',
    layout: 'graph',
    colgap: 170,
    cardMax: 320,
    rowgap: 16,
    columns: [
      { nodes: [{ id: 'user', icon: 'user', title: 'User Request' }] },
      { nodes: [{ id: 'main', icon: 'target', title: 'Main Agent', accent: true }] },
      {
        nodes: [
          { id: 'mem', icon: 'database', title: 'Memory', chip: 'context' },
          { id: 'mcp', icon: 'server', title: 'MCP', chip: 'live data' },
          { id: 'skills', icon: 'star', title: 'Skills', chip: 'auto tools' },
          { id: 'sub', icon: 'users', title: 'Subagents', chip: 'specialists' },
        ],
      },
      { nodes: [{ id: 'ctx', icon: 'layers', title: 'Clean Context Window', chip: 'isolated' }] },
    ],
    edges: [
      { from: 'user', to: 'main' },
      { from: 'main', to: 'mem', label: 'uses' },
      { from: 'main', to: 'mcp', label: 'queries' },
      { from: 'main', to: 'skills', label: 'invokes' },
      { from: 'main', to: 'sub', label: 'delegates' },
      { from: 'sub', to: 'ctx', label: 'isolated' },
    ],
    footer: 'Subagents also use memory and query MCP, just like the main agent.',
  },
  {
    name: 'mcp-direct-tool-calls',
    alt: 'Direct MCP tool calls: the model calls getDocument and gets the full 50K-token transcript back, then calls updateRecord and re-sends the whole transcript, so large data passes through the model twice',
    eyebrow: 'MCP · Direct Tool Calls',
    title: 'Every result goes [[through the model]]',
    sub: 'With direct tool calls, large data passes through the context window, sometimes twice.',
    layout: 'sequence',
    rowH: 62,
    participants: [
      { id: 'model', icon: 'cpu', title: 'Model', accent: true },
      { id: 'mcp', icon: 'server', title: 'MCP Server' },
    ],
    steps: [
      { from: 'model', to: 'mcp', label: 'Tool call: getDocument' },
      { from: 'mcp', to: 'model', label: 'Full transcript (50K tokens)', dashed: true },
      { from: 'model', to: 'mcp', label: 'Tool call: updateRecord (re-sends full transcript)' },
      { from: 'mcp', to: 'model', label: 'Confirmation', dashed: true },
    ],
  },
  {
    name: 'mcp-code-execution',
    alt: 'MCP with code execution: the model writes code that runs in an execution environment; that code calls MCP tools directly, the data stays in the environment, and only the final result, using few tokens, returns to the model',
    eyebrow: 'MCP · Code Execution',
    title: 'Data stays [[out of the context]]',
    sub: 'The model writes code; the code calls the tools and returns only what matters.',
    layout: 'graph',
    colgap: 230,
    cardMax: 330,
    columns: [
      { nodes: [{ id: 'model', icon: 'cpu', title: 'Model', chip: 'writes code' }] },
      { nodes: [{ id: 'env', icon: 'code', title: 'Code Execution', chip: 'environment', accent: true }] },
      { nodes: [{ id: 'mcp', icon: 'server', title: 'MCP Servers' }] },
    ],
    edges: [
      { from: 'model', to: 'env', label: 'writes code' },
      { from: 'env', to: 'model', label: 'final result only', dashed: true },
      { from: 'env', to: 'mcp', label: 'calls tools' },
      { from: 'mcp', to: 'env', label: 'data stays here', dashed: true },
    ],
    footer: '<b>Result</b> only the final answer reaches the model, using minimal tokens',
  },
  {
    name: 'cli-architecture',
    alt: 'Claude Code CLI architecture: running claude with options starts interactive REPL mode, print mode with --print, or a resumed session with --resume; each talks to the Claude API, and the output goes to the terminal or a pipe as text, JSON, or stream-JSON',
    eyebrow: 'CLI · Architecture',
    title: 'How the [[claude]] command works',
    sub: 'One command, three ways to run, one API behind them.',
    layout: 'graph',
    colgap: 150,
    cardMax: 280,
    rowgap: 18,
    dense: true,
    columns: [
      { nodes: [{ id: 'term', icon: 'terminal', title: 'Terminal', chip: 'claude' }] },
      { nodes: [{ id: 'cli', icon: 'cpu', title: 'Claude Code CLI' }] },
      {
        nodes: [
          { id: 'repl', icon: 'message', title: 'REPL Mode', chip: 'interactive' },
          { id: 'print', icon: 'file', title: 'Print Mode', chip: '--print' },
          { id: 'resume', icon: 'refresh', title: 'Session Resume', chip: '--resume' },
        ],
      },
      { nodes: [{ id: 'api', icon: 'globe', title: 'Claude API', accent: true }] },
      { nodes: [{ id: 'out', icon: 'send', title: 'Output', desc: 'text · json · stream-json' }] },
      { nodes: [{ id: 'pipe', icon: 'terminal', title: 'Terminal / Pipe' }] },
    ],
    edges: [
      { from: 'term', to: 'cli' },
      { from: 'cli', to: 'repl' },
      { from: 'cli', to: 'print' },
      { from: 'cli', to: 'resume' },
      { from: 'repl', to: 'api' },
      { from: 'print', to: 'api' },
      { from: 'resume', to: 'api' },
      { from: 'api', to: 'out', label: 'response' },
      { from: 'out', to: 'pipe' },
    ],
    footer: '<b>REPL</b> holds a conversation &nbsp;·&nbsp; <b>Print</b> sends a single query &nbsp;·&nbsp; <b>Resume</b> loads saved context',
  },
  {
    name: 'cli-modes',
    alt: 'Claude CLI modes: by default claude opens an interactive REPL with multi-turn conversation, tab completion, history, and slash commands; with -p it runs in print mode for a single query that is scriptable, pipeable, and can output JSON',
    eyebrow: 'CLI · Modes',
    title: 'Interactive or [[print mode]]',
    sub: 'Chat back and forth, or run one query and get the answer.',
    layout: 'graph',
    colgap: 200,
    cardMax: 420,
    rowgap: 40,
    columns: [
      { nodes: [{ id: 'c', icon: 'terminal', title: 'claude' }] },
      {
        nodes: [
          { id: 'repl', icon: 'message', title: 'Interactive REPL', chip: 'default', desc: 'Multi-turn conversation · tab completion · history · slash commands' },
          { id: 'print', icon: 'file', title: 'Print Mode', chip: 'claude -p', desc: 'Single query · scriptable · pipeable · JSON output', accent: true },
        ],
      },
    ],
    edges: [
      { from: 'c', to: 'repl', label: 'default' },
      { from: 'c', to: 'print', label: '-p flag' },
    ],
  },
  {
    name: 'new-repo-workflow',
    alt: 'Starting a new repository with Claude Code in four phases: set up the repo and CLAUDE.md, plan the feature in plan mode, build each feature chunk with code, tests, and review until done, then set up CI/CD so the repository is ready',
    eyebrow: 'Workflow · New Repository',
    title: 'Starting a [[new repository]]',
    sub: 'Four phases, from an empty folder to a repo with CI/CD.',
    layout: 'graph',
    colgap: 60,
    cardMax: 300,
    rowgap: 12,
    dense: true,
    columns: [
      {
        label: '1 · Set up',
        nodes: [
          { id: 'a', icon: 'folder', title: 'Start new repo', chip: 'README · LICENSE' },
          { id: 'b', icon: 'file', title: 'Create CLAUDE.md', chip: 'architecture & guidelines' },
          { id: 'c', icon: 'download', title: 'Install Claude Code' },
        ],
      },
      {
        label: '2 · Plan',
        nodes: [
          { id: 'd', icon: 'eye', title: 'Enter plan mode' },
          { id: 'e', icon: 'edit', title: 'Draft feature spec' },
          { id: 'f', icon: 'layers', title: 'Define components', chip: 'architecture ideas' },
        ],
      },
      {
        label: '3 · Build (repeat)',
        nodes: [
          { id: 'g', icon: 'code', title: 'Generate code' },
          { id: 'h', icon: 'check', title: 'Request unit tests' },
          { id: 'i', icon: 'search', title: 'Review & refactor' },
          { id: 'q', q: true, title: 'More features?' },
        ],
      },
      {
        label: '4 · Ship',
        nodes: [
          { id: 'j', icon: 'list', title: 'Update task list', chip: 'in CLAUDE.md' },
          { id: 'k', icon: 'git', title: 'Set up CI/CD', chip: 'GitHub Actions' },
          { id: 'l', icon: 'send', title: 'Deployment scripts', chip: '+ test automation' },
          { id: 'z', icon: 'check', title: 'Repository ready', accent: true },
        ],
      },
    ],
    edges: [
      { from: 'a', to: 'b' }, { from: 'b', to: 'c' },
      { from: 'c', to: 'd' }, { from: 'd', to: 'e' }, { from: 'e', to: 'f' },
      { from: 'f', to: 'g' }, { from: 'g', to: 'h' }, { from: 'h', to: 'i' }, { from: 'i', to: 'q' },
      { from: 'q', to: 'j', label: 'no' },
      { from: 'j', to: 'k' }, { from: 'k', to: 'l' }, { from: 'l', to: 'z' },
    ],
    footer: '<b>More features?</b> If yes, build the next chunk: loop back to <b>Generate code</b>.',
  },
  {
    name: 'existing-repo-workflow',
    alt: 'Working in an existing repository with Claude Code in four phases: document the codebase in CLAUDE.md (or CLAUDE_LEGACY.md for legacy code) and pin key files; pick the task type and set clear boundaries; use git worktrees and separate sessions for parallel features; then set up team automation with shared commands and hooks',
    eyebrow: 'Workflow · Existing Repository',
    title: 'Working in an [[existing repository]]',
    sub: 'Give Claude context, pick the task, run work in parallel, then automate for the team.',
    layout: 'graph',
    colgap: 56,
    cardMax: 300,
    rowgap: 12,
    dense: true,
    columns: [
      {
        label: '1 · Context',
        nodes: [
          { id: 'a', q: true, title: 'Legacy codebase?' },
          { id: 'b', icon: 'file', title: 'CLAUDE_LEGACY.md', chip: 'yes · versions' },
          { id: 'c', icon: 'file', title: 'CLAUDE.md', chip: 'no · structure' },
          { id: 'd', icon: 'link', title: 'Pin key files' },
        ],
      },
      {
        label: '2 · Task',
        nodes: [
          { id: 'e', q: true, title: 'Task type?' },
          { id: 'f', icon: 'tool', title: 'Bug fix · Review', chip: 'analysis' },
          { id: 'g', icon: 'refresh', title: 'Refactor · Migrate', chip: 'make a plan' },
          { id: 'h', icon: 'shield', title: 'Set boundaries', chip: 'explicit scope' },
        ],
      },
      {
        label: '3 · Parallel work',
        nodes: [
          { id: 'i', q: true, title: 'Multiple features?' },
          { id: 'j', icon: 'git', title: 'Git worktrees', chip: 'yes · one per feature' },
          { id: 'k', icon: 'monitor', title: 'Main branch', chip: 'no' },
          { id: 'l', icon: 'grid', title: 'Organize sessions', chip: 'terminal tabs' },
        ],
      },
      {
        label: '4 · Team',
        nodes: [
          { id: 'm', icon: 'users', title: 'Sync commands', chip: '.claude/commands/' },
          { id: 'n', icon: 'zap', title: 'Set up hooks' },
          { id: 'o', icon: 'message', title: 'Share context', chip: 'with the team' },
          { id: 'z', icon: 'check', title: 'Workflow complete', accent: true },
        ],
      },
    ],
    edges: [
      { from: 'a', to: 'b' }, { from: 'a', to: 'c' }, { from: 'b', to: 'd' }, { from: 'c', to: 'd' },
      { from: 'd', to: 'e' }, { from: 'e', to: 'f' }, { from: 'f', to: 'g' }, { from: 'g', to: 'h' },
      { from: 'h', to: 'i' }, { from: 'i', to: 'j' }, { from: 'j', to: 'k' }, { from: 'k', to: 'l' },
      { from: 'l', to: 'm' }, { from: 'm', to: 'n' }, { from: 'n', to: 'o' }, { from: 'o', to: 'z' },
    ],
    footer: '<b>More tasks?</b> Go back to <b>Task type?</b> and repeat.',
  },
];
